WITH december_events AS (
    SELECT "EVENT_NAME", "EVENT_TIMESTAMP", "ITEMS"
      FROM GA4.GA4_OBFUSCATED_SAMPLE_ECOMMERCE."EVENTS_20201201"
    UNION ALL SELECT "EVENT_NAME", "EVENT_TIMESTAMP", "ITEMS" FROM GA4.GA4_OBFUSCATED_SAMPLE_ECOMMERCE."EVENTS_20201202"
    UNION ALL SELECT "EVENT_NAME", "EVENT_TIMESTAMP", "ITEMS" FROM GA4.GA4_OBFUSCATED_SAMPLE_ECOMMERCE."EVENTS_20201203"
    UNION ALL SELECT "EVENT_NAME", "EVENT_TIMESTAMP", "ITEMS" FROM GA4.GA4_OBFUSCATED_SAMPLE_ECOMMERCE."EVENTS_20201204"
    UNION ALL SELECT "EVENT_NAME", "EVENT_TIMESTAMP", "ITEMS" FROM GA4.GA4_OBFUSCATED_SAMPLE_ECOMMERCE."EVENTS_20201205"
    UNION ALL SELECT "EVENT_NAME", "EVENT_TIMESTAMP", "ITEMS" FROM GA4.GA4_OBFUSCATED_SAMPLE_ECOMMERCE."EVENTS_20201206"
    UNION ALL SELECT "EVENT_NAME", "EVENT_TIMESTAMP", "ITEMS" FROM GA4.GA4_OBFUSCATED_SAMPLE_ECOMMERCE."EVENTS_20201207"
    UNION ALL SELECT "EVENT_NAME", "EVENT_TIMESTAMP", "ITEMS" FROM GA4.GA4_OBFUSCATED_SAMPLE_ECOMMERCE."EVENTS_20201208"
    UNION ALL SELECT "EVENT_NAME", "EVENT_TIMESTAMP", "ITEMS" FROM GA4.GA4_OBFUSCATED_SAMPLE_ECOMMERCE."EVENTS_20201209"
    UNION ALL SELECT "EVENT_NAME", "EVENT_TIMESTAMP", "ITEMS" FROM GA4.GA4_OBFUSCATED_SAMPLE_ECOMMERCE."EVENTS_20201210"
    UNION ALL SELECT "EVENT_NAME", "EVENT_TIMESTAMP", "ITEMS" FROM GA4.GA4_OBFUSCATED_SAMPLE_ECOMMERCE."EVENTS_20201211"
    UNION ALL SELECT "EVENT_NAME", "EVENT_TIMESTAMP", "ITEMS" FROM GA4.GA4_OBFUSCATED_SAMPLE_ECOMMERCE."EVENTS_20201212"
    UNION ALL SELECT "EVENT_NAME", "EVENT_TIMESTAMP", "ITEMS" FROM GA4.GA4_OBFUSCATED_SAMPLE_ECOMMERCE."EVENTS_20201213"
    UNION ALL SELECT "EVENT_NAME", "EVENT_TIMESTAMP", "ITEMS" FROM GA4.GA4_OBFUSCATED_SAMPLE_ECOMMERCE."EVENTS_20201214"
    UNION ALL SELECT "EVENT_NAME", "EVENT_TIMESTAMP", "ITEMS" FROM GA4.GA4_OBFUSCATED_SAMPLE_ECOMMERCE."EVENTS_20201215"
    UNION ALL SELECT "EVENT_NAME", "EVENT_TIMESTAMP", "ITEMS" FROM GA4.GA4_OBFUSCATED_SAMPLE_ECOMMERCE."EVENTS_20201216"
    UNION ALL SELECT "EVENT_NAME", "EVENT_TIMESTAMP", "ITEMS" FROM GA4.GA4_OBFUSCATED_SAMPLE_ECOMMERCE."EVENTS_20201217"
    UNION ALL SELECT "EVENT_NAME", "EVENT_TIMESTAMP", "ITEMS" FROM GA4.GA4_OBFUSCATED_SAMPLE_ECOMMERCE."EVENTS_20201218"
    UNION ALL SELECT "EVENT_NAME", "EVENT_TIMESTAMP", "ITEMS" FROM GA4.GA4_OBFUSCATED_SAMPLE_ECOMMERCE."EVENTS_20201219"
    UNION ALL SELECT "EVENT_NAME", "EVENT_TIMESTAMP", "ITEMS" FROM GA4.GA4_OBFUSCATED_SAMPLE_ECOMMERCE."EVENTS_20201220"
    UNION ALL SELECT "EVENT_NAME", "EVENT_TIMESTAMP", "ITEMS" FROM GA4.GA4_OBFUSCATED_SAMPLE_ECOMMERCE."EVENTS_20201221"
    UNION ALL SELECT "EVENT_NAME", "EVENT_TIMESTAMP", "ITEMS" FROM GA4.GA4_OBFUSCATED_SAMPLE_ECOMMERCE."EVENTS_20201222"
    UNION ALL SELECT "EVENT_NAME", "EVENT_TIMESTAMP", "ITEMS" FROM GA4.GA4_OBFUSCATED_SAMPLE_ECOMMERCE."EVENTS_20201223"
    UNION ALL SELECT "EVENT_NAME", "EVENT_TIMESTAMP", "ITEMS" FROM GA4.GA4_OBFUSCATED_SAMPLE_ECOMMERCE."EVENTS_20201224"
    UNION ALL SELECT "EVENT_NAME", "EVENT_TIMESTAMP", "ITEMS" FROM GA4.GA4_OBFUSCATED_SAMPLE_ECOMMERCE."EVENTS_20201225"
    UNION ALL SELECT "EVENT_NAME", "EVENT_TIMESTAMP", "ITEMS" FROM GA4.GA4_OBFUSCATED_SAMPLE_ECOMMERCE."EVENTS_20201226"
    UNION ALL SELECT "EVENT_NAME", "EVENT_TIMESTAMP", "ITEMS" FROM GA4.GA4_OBFUSCATED_SAMPLE_ECOMMERCE."EVENTS_20201227"
    UNION ALL SELECT "EVENT_NAME", "EVENT_TIMESTAMP", "ITEMS" FROM GA4.GA4_OBFUSCATED_SAMPLE_ECOMMERCE."EVENTS_20201228"
    UNION ALL SELECT "EVENT_NAME", "EVENT_TIMESTAMP", "ITEMS" FROM GA4.GA4_OBFUSCATED_SAMPLE_ECOMMERCE."EVENTS_20201229"
    UNION ALL SELECT "EVENT_NAME", "EVENT_TIMESTAMP", "ITEMS" FROM GA4.GA4_OBFUSCATED_SAMPLE_ECOMMERCE."EVENTS_20201230"
    UNION ALL SELECT "EVENT_NAME", "EVENT_TIMESTAMP", "ITEMS" FROM GA4.GA4_OBFUSCATED_SAMPLE_ECOMMERCE."EVENTS_20201231"
),
purchase_items AS (
    SELECT
        de."EVENT_TIMESTAMP",
        f.value:"item_name"::string                      AS item_name,
        COALESCE(f.value:"quantity"::number, 1)         AS quantity
    FROM december_events de,
         LATERAL FLATTEN(input => de."ITEMS") f
    WHERE de."EVENT_NAME" = 'purchase'
),
target_purchase_ids AS (
    SELECT DISTINCT "EVENT_TIMESTAMP"
      FROM purchase_items
     WHERE item_name = 'Google Navy Speckled Tee'
),
other_products AS (
    SELECT
        p.item_name,
        SUM(p.quantity) AS total_quantity
      FROM purchase_items p
      JOIN target_purchase_ids t
        ON p."EVENT_TIMESTAMP" = t."EVENT_TIMESTAMP"
     WHERE p.item_name <> 'Google Navy Speckled Tee'
  GROUP BY p.item_name
)
SELECT
    item_name      AS "OTHER_PRODUCT",
    total_quantity AS "TOTAL_QUANTITY"
  FROM other_products
 ORDER BY total_quantity DESC NULLS LAST
 LIMIT 1;