/*-----------------------------------------------------------
  What other product was most frequently bought together with
  the “Google Navy Speckled Tee” in December-2020 purchases?
-----------------------------------------------------------*/
WITH december_events AS (      -- all December 2020 event tables
    SELECT "EVENT_TIMESTAMP","EVENT_NAME","ITEMS" FROM GA4.GA4_OBFUSCATED_SAMPLE_ECOMMERCE."EVENTS_20201201"
    UNION ALL SELECT "EVENT_TIMESTAMP","EVENT_NAME","ITEMS" FROM GA4.GA4_OBFUSCATED_SAMPLE_ECOMMERCE."EVENTS_20201202"
    UNION ALL SELECT "EVENT_TIMESTAMP","EVENT_NAME","ITEMS" FROM GA4.GA4_OBFUSCATED_SAMPLE_ECOMMERCE."EVENTS_20201203"
    UNION ALL SELECT "EVENT_TIMESTAMP","EVENT_NAME","ITEMS" FROM GA4.GA4_OBFUSCATED_SAMPLE_ECOMMERCE."EVENTS_20201204"
    UNION ALL SELECT "EVENT_TIMESTAMP","EVENT_NAME","ITEMS" FROM GA4.GA4_OBFUSCATED_SAMPLE_ECOMMERCE."EVENTS_20201205"
    UNION ALL SELECT "EVENT_TIMESTAMP","EVENT_NAME","ITEMS" FROM GA4.GA4_OBFUSCATED_SAMPLE_ECOMMERCE."EVENTS_20201206"
    UNION ALL SELECT "EVENT_TIMESTAMP","EVENT_NAME","ITEMS" FROM GA4.GA4_OBFUSCATED_SAMPLE_ECOMMERCE."EVENTS_20201207"
    UNION ALL SELECT "EVENT_TIMESTAMP","EVENT_NAME","ITEMS" FROM GA4.GA4_OBFUSCATED_SAMPLE_ECOMMERCE."EVENTS_20201208"
    UNION ALL SELECT "EVENT_TIMESTAMP","EVENT_NAME","ITEMS" FROM GA4.GA4_OBFUSCATED_SAMPLE_ECOMMERCE."EVENTS_20201209"
    UNION ALL SELECT "EVENT_TIMESTAMP","EVENT_NAME","ITEMS" FROM GA4.GA4_OBFUSCATED_SAMPLE_ECOMMERCE."EVENTS_20201210"
    UNION ALL SELECT "EVENT_TIMESTAMP","EVENT_NAME","ITEMS" FROM GA4.GA4_OBFUSCATED_SAMPLE_ECOMMERCE."EVENTS_20201211"
    UNION ALL SELECT "EVENT_TIMESTAMP","EVENT_NAME","ITEMS" FROM GA4.GA4_OBFUSCATED_SAMPLE_ECOMMERCE."EVENTS_20201212"
    UNION ALL SELECT "EVENT_TIMESTAMP","EVENT_NAME","ITEMS" FROM GA4.GA4_OBFUSCATED_SAMPLE_ECOMMERCE."EVENTS_20201213"
    UNION ALL SELECT "EVENT_TIMESTAMP","EVENT_NAME","ITEMS" FROM GA4.GA4_OBFUSCATED_SAMPLE_ECOMMERCE."EVENTS_20201214"
    UNION ALL SELECT "EVENT_TIMESTAMP","EVENT_NAME","ITEMS" FROM GA4.GA4_OBFUSCATED_SAMPLE_ECOMMERCE."EVENTS_20201215"
    UNION ALL SELECT "EVENT_TIMESTAMP","EVENT_NAME","ITEMS" FROM GA4.GA4_OBFUSCATED_SAMPLE_ECOMMERCE."EVENTS_20201216"
    UNION ALL SELECT "EVENT_TIMESTAMP","EVENT_NAME","ITEMS" FROM GA4.GA4_OBFUSCATED_SAMPLE_ECOMMERCE."EVENTS_20201217"
    UNION ALL SELECT "EVENT_TIMESTAMP","EVENT_NAME","ITEMS" FROM GA4.GA4_OBFUSCATED_SAMPLE_ECOMMERCE."EVENTS_20201218"
    UNION ALL SELECT "EVENT_TIMESTAMP","EVENT_NAME","ITEMS" FROM GA4.GA4_OBFUSCATED_SAMPLE_ECOMMERCE."EVENTS_20201219"
    UNION ALL SELECT "EVENT_TIMESTAMP","EVENT_NAME","ITEMS" FROM GA4.GA4_OBFUSCATED_SAMPLE_ECOMMERCE."EVENTS_20201220"
    UNION ALL SELECT "EVENT_TIMESTAMP","EVENT_NAME","ITEMS" FROM GA4.GA4_OBFUSCATED_SAMPLE_ECOMMERCE."EVENTS_20201221"
    UNION ALL SELECT "EVENT_TIMESTAMP","EVENT_NAME","ITEMS" FROM GA4.GA4_OBFUSCATED_SAMPLE_ECOMMERCE."EVENTS_20201222"
    UNION ALL SELECT "EVENT_TIMESTAMP","EVENT_NAME","ITEMS" FROM GA4.GA4_OBFUSCATED_SAMPLE_ECOMMERCE."EVENTS_20201223"
    UNION ALL SELECT "EVENT_TIMESTAMP","EVENT_NAME","ITEMS" FROM GA4.GA4_OBFUSCATED_SAMPLE_ECOMMERCE."EVENTS_20201224"
    UNION ALL SELECT "EVENT_TIMESTAMP","EVENT_NAME","ITEMS" FROM GA4.GA4_OBFUSCATED_SAMPLE_ECOMMERCE."EVENTS_20201225"
    UNION ALL SELECT "EVENT_TIMESTAMP","EVENT_NAME","ITEMS" FROM GA4.GA4_OBFUSCATED_SAMPLE_ECOMMERCE."EVENTS_20201226"
    UNION ALL SELECT "EVENT_TIMESTAMP","EVENT_NAME","ITEMS" FROM GA4.GA4_OBFUSCATED_SAMPLE_ECOMMERCE."EVENTS_20201227"
    UNION ALL SELECT "EVENT_TIMESTAMP","EVENT_NAME","ITEMS" FROM GA4.GA4_OBFUSCATED_SAMPLE_ECOMMERCE."EVENTS_20201228"
    UNION ALL SELECT "EVENT_TIMESTAMP","EVENT_NAME","ITEMS" FROM GA4.GA4_OBFUSCATED_SAMPLE_ECOMMERCE."EVENTS_20201229"
    UNION ALL SELECT "EVENT_TIMESTAMP","EVENT_NAME","ITEMS" FROM GA4.GA4_OBFUSCATED_SAMPLE_ECOMMERCE."EVENTS_20201230"
    UNION ALL SELECT "EVENT_TIMESTAMP","EVENT_NAME","ITEMS" FROM GA4.GA4_OBFUSCATED_SAMPLE_ECOMMERCE."EVENTS_20201231"
),

/* purchase events that include the target tee ---------------------------------------*/
tee_purchase_events AS (
    SELECT DISTINCT e."EVENT_TIMESTAMP"
    FROM december_events            AS e,
         LATERAL FLATTEN(input => e."ITEMS") AS f
    WHERE e."EVENT_NAME" = 'purchase'
      AND f.value:"item_name"::string = 'Google Navy Speckled Tee'
),

/* all other items bought in those same purchase events ------------------------------*/
other_items AS (
    SELECT
        f.value:"item_name"::string                                  AS other_product,
        SUM(COALESCE(f.value:"quantity"::number, 1))                AS total_quantity
    FROM december_events               AS e
    JOIN tee_purchase_events           AS p
      ON e."EVENT_TIMESTAMP" = p."EVENT_TIMESTAMP",
         LATERAL FLATTEN(input => e."ITEMS") AS f
    WHERE f.value:"item_name"::string <> 'Google Navy Speckled Tee'
    GROUP BY other_product
)

/* top co-purchased product -----------------------------------------------------------*/
SELECT other_product            AS "PRODUCT_NAME",
       total_quantity           AS "TOTAL_QUANTITY"
FROM other_items
ORDER BY total_quantity DESC NULLS LAST
LIMIT 1;