SELECT 
    "USER_ID",
    "PLATFORM",
    "CAMPAIGN_ID",
    "MESSAGE_VARIATION_ID",
    "BROWSER",
    "DEVICE_MODEL",
    "CARRIER",
    "TIME",
    "APP_GROUP_ID"
FROM (
    SELECT 
        "USER_ID",
        "PLATFORM",
        "CAMPAIGN_ID",
        "MESSAGE_VARIATION_ID",
        "BROWSER",
        "DEVICE_MODEL",
        "CARRIER",
        "TIME",
        "APP_GROUP_ID"
    FROM BRAZE_USER_EVENT_DEMO_DATASET.PUBLIC.USERS_MESSAGES_PUSHNOTIFICATION_OPEN_VIEW

    UNION ALL

    SELECT 
        "USER_ID",
        "PLATFORM",
        "CAMPAIGN_ID",
        NULL AS "MESSAGE_VARIATION_ID",
        NULL AS "BROWSER",
        NULL AS "DEVICE_MODEL",
        NULL AS "CARRIER",
        "TIME",
        "APP_GROUP_ID"
    FROM BRAZE_USER_EVENT_DEMO_DATASET.PUBLIC.USERS_MESSAGES_PUSHNOTIFICATION_SEND_VIEW

    UNION ALL

    SELECT 
        "USER_ID",
        "PLATFORM",
        "CAMPAIGN_ID",
        "MESSAGE_VARIATION_ID",
        "BROWSER",
        "DEVICE_MODEL",
        "CARRIER",
        "TIME",
        "APP_GROUP_ID"
    FROM BRAZE_USER_EVENT_DEMO_DATASET.PUBLIC.USERS_MESSAGES_PUSHNOTIFICATION_INFLUENCEDOPEN_VIEW

    UNION ALL

    SELECT 
        "USER_ID",
        "PLATFORM",
        "CAMPAIGN_ID",
        "MESSAGE_VARIATION_ID",
        NULL AS "BROWSER",
        NULL AS "DEVICE_MODEL",
        NULL AS "CARRIER",
        "TIME",
        "APP_GROUP_ID"
    FROM BRAZE_USER_EVENT_DEMO_DATASET.PUBLIC.USERS_MESSAGES_PUSHNOTIFICATION_BOUNCE_VIEW
) AS COMBINED_EVENTS
WHERE "TIME" BETWEEN 1685606400 AND 1685610000
ORDER BY "TIME" ASC;