WITH PUSH_NOTIFICATION_EVENTS AS (
    SELECT "APP_GROUP_ID", "CAMPAIGN_ID", "USER_ID", "MESSAGE_VARIATION_ID", "PLATFORM", 
           NULL AS "AD_TRACKING_ENABLED", NULL AS "CARRIER", NULL AS "BROWSER", NULL AS "DEVICE_MODEL", 
           'send_event' AS "EVENT_TYPE", 1 AS "EVENT_COUNT"
    FROM BRAZE_USER_EVENT_DEMO_DATASET.PUBLIC.USERS_MESSAGES_PUSHNOTIFICATION_SEND_VIEW
    WHERE "TIME" BETWEEN 1685606400 AND 1685610000

    UNION ALL

    SELECT "APP_GROUP_ID", "CAMPAIGN_ID", "USER_ID", "MESSAGE_VARIATION_ID", "PLATFORM", 
           NULL AS "AD_TRACKING_ENABLED", NULL AS "CARRIER", NULL AS "BROWSER", NULL AS "DEVICE_MODEL", 
           'bounce_event' AS "EVENT_TYPE", 1 AS "EVENT_COUNT"
    FROM BRAZE_USER_EVENT_DEMO_DATASET.PUBLIC.USERS_MESSAGES_PUSHNOTIFICATION_BOUNCE_VIEW
    WHERE "TIME" BETWEEN 1685606400 AND 1685610000

    UNION ALL

    SELECT "APP_GROUP_ID", "CAMPAIGN_ID", "USER_ID", "MESSAGE_VARIATION_ID", "PLATFORM", 
           NULL AS "AD_TRACKING_ENABLED", "CARRIER", "BROWSER", "DEVICE_MODEL", 
           'open_event' AS "EVENT_TYPE", 1 AS "EVENT_COUNT"
    FROM BRAZE_USER_EVENT_DEMO_DATASET.PUBLIC.USERS_MESSAGES_PUSHNOTIFICATION_OPEN_VIEW
    WHERE "TIME" BETWEEN 1685606400 AND 1685610000

    UNION ALL

    SELECT "APP_GROUP_ID", "CAMPAIGN_ID", "USER_ID", "MESSAGE_VARIATION_ID", "PLATFORM", 
           NULL AS "AD_TRACKING_ENABLED", "CARRIER", "BROWSER", "DEVICE_MODEL", 
           'influenced_open_event' AS "EVENT_TYPE", 1 AS "EVENT_COUNT"
    FROM BRAZE_USER_EVENT_DEMO_DATASET.PUBLIC.USERS_MESSAGES_PUSHNOTIFICATION_INFLUENCEDOPEN_VIEW
    WHERE "TIME" BETWEEN 1685606400 AND 1685610000
)
SELECT 
    "APP_GROUP_ID", 
    "CAMPAIGN_ID", 
    "USER_ID", 
    "MESSAGE_VARIATION_ID", 
    "PLATFORM", 
    MAX("CARRIER") AS "CARRIER",
    MAX("BROWSER") AS "BROWSER",
    MAX("DEVICE_MODEL") AS "DEVICE_MODEL",
    COUNT(CASE WHEN "EVENT_TYPE" = 'send_event' THEN "EVENT_COUNT" ELSE NULL END) AS "push_notification_sends",
    COUNT(DISTINCT CASE WHEN "EVENT_TYPE" = 'send_event' THEN "USER_ID" ELSE NULL END) AS "unique_push_notification_sends",
    COUNT(CASE WHEN "EVENT_TYPE" = 'bounce_event' THEN "EVENT_COUNT" ELSE NULL END) AS "push_notification_bounced",
    COUNT(DISTINCT CASE WHEN "EVENT_TYPE" = 'bounce_event' THEN "USER_ID" ELSE NULL END) AS "unique_push_notification_bounced",
    COUNT(CASE WHEN "EVENT_TYPE" = 'open_event' THEN "EVENT_COUNT" ELSE NULL END) AS "push_notification_open",
    COUNT(DISTINCT CASE WHEN "EVENT_TYPE" = 'open_event' THEN "USER_ID" ELSE NULL END) AS "unique_push_notification_opened",
    COUNT(CASE WHEN "EVENT_TYPE" = 'influenced_open_event' THEN "EVENT_COUNT" ELSE NULL END) AS "push_notification_influenced_open",
    COUNT(DISTINCT CASE WHEN "EVENT_TYPE" = 'influenced_open_event' THEN "USER_ID" ELSE NULL END) AS "unique_push_notification_influenced_open"
FROM PUSH_NOTIFICATION_EVENTS
GROUP BY 
    "APP_GROUP_ID", 
    "CAMPAIGN_ID", 
    "USER_ID", 
    "MESSAGE_VARIATION_ID", 
    "PLATFORM"
ORDER BY "APP_GROUP_ID", "CAMPAIGN_ID", "USER_ID"
LIMIT 20;