SELECT 
    "USER_ID", 
    "CAMPAIGN_ID", 
    "PLATFORM",
    "MESSAGE_VARIATION_ID",
    "TIME", 
    "ID"
FROM 
    (
        SELECT "USER_ID", "CAMPAIGN_ID", "PLATFORM", "MESSAGE_VARIATION_ID", "TIME", "ID" 
        FROM BRAZE_USER_EVENT_DEMO_DATASET.PUBLIC.USERS_MESSAGES_PUSHNOTIFICATION_SEND_VIEW
        UNION ALL
        SELECT "USER_ID", "CAMPAIGN_ID", "PLATFORM", "MESSAGE_VARIATION_ID", "TIME", "ID"
        FROM BRAZE_USER_EVENT_DEMO_DATASET.PUBLIC.USERS_MESSAGES_PUSHNOTIFICATION_BOUNCE_VIEW
        UNION ALL
        SELECT "USER_ID", "CAMPAIGN_ID", "PLATFORM", "MESSAGE_VARIATION_ID", "TIME", "ID"
        FROM BRAZE_USER_EVENT_DEMO_DATASET.PUBLIC.USERS_MESSAGES_PUSHNOTIFICATION_OPEN_VIEW
        UNION ALL
        SELECT "USER_ID", "CAMPAIGN_ID", "PLATFORM", "MESSAGE_VARIATION_ID", "TIME", "ID"
        FROM BRAZE_USER_EVENT_DEMO_DATASET.PUBLIC.USERS_MESSAGES_PUSHNOTIFICATION_INFLUENCEDOPEN_VIEW
    ) 
WHERE "TIME" >= 1685606400 AND "TIME" <= 1685610000
ORDER BY "TIME" ASC
LIMIT 50;