SELECT DISTINCT 
    "USER_ID", 
    "CAMPAIGN_ID", 
    "MESSAGE_VARIATION_API_ID", 
    "PLATFORM", 
    "TIME" 
FROM (
    -- Union all relevant tables related to user engagement with push notifications
    SELECT "USER_ID", "CAMPAIGN_ID", "MESSAGE_VARIATION_API_ID", "PLATFORM", "TIME"
    FROM "BRAZE_USER_EVENT_DEMO_DATASET"."PUBLIC"."USERS_MESSAGES_PUSHNOTIFICATION_OPEN_VIEW"
    UNION ALL
    SELECT "USER_ID", "CAMPAIGN_ID", "MESSAGE_VARIATION_API_ID", "PLATFORM", "TIME"
    FROM "BRAZE_USER_EVENT_DEMO_DATASET"."PUBLIC"."USERS_MESSAGES_PUSHNOTIFICATION_INFLUENCEDOPEN_VIEW"
    UNION ALL
    SELECT "USER_ID", "CAMPAIGN_ID", "MESSAGE_VARIATION_API_ID", "PLATFORM", "TIME"
    FROM "BRAZE_USER_EVENT_DEMO_DATASET"."PUBLIC"."USERS_MESSAGES_PUSHNOTIFICATION_SEND_VIEW"
    UNION ALL
    SELECT "USER_ID", "CAMPAIGN_ID", "MESSAGE_VARIATION_API_ID", "PLATFORM", "TIME"
    FROM "BRAZE_USER_EVENT_DEMO_DATASET"."PUBLIC"."USERS_MESSAGES_PUSHNOTIFICATION_INFLUENCEDOPEN_SHARED_VIEW"
    UNION ALL
    SELECT "USER_ID", "CAMPAIGN_ID", "MESSAGE_VARIATION_API_ID", "PLATFORM", "TIME"
    FROM "BRAZE_USER_EVENT_DEMO_DATASET"."PUBLIC"."USERS_MESSAGES_PUSHNOTIFICATION_SEND_SHARED_VIEW"
) UNIONED_TABLE
WHERE "TIME" BETWEEN 1685616000 AND 1685619600 -- June 1, 2023, 8:00 AM to 9:00 AM (UNIX TIMESTAMP)
ORDER BY "TIME" ASC
LIMIT 20;