SELECT 
    "USER_ID",
    "PLATFORM",
    "APP_GROUP_ID",
    "CAMPAIGN_ID",
    "MESSAGE_VARIATION_ID",
    COUNT(*) AS "EVENT_COUNT"
FROM (
    -- Combine all relevant views for engagement event types
    SELECT 
        "USER_ID",
        "PLATFORM",
        "APP_GROUP_ID",
        "CAMPAIGN_ID",
        "MESSAGE_VARIATION_ID",
        "TIME"
    FROM BRAZE_USER_EVENT_DEMO_DATASET.PUBLIC.USERS_MESSAGES_PUSHNOTIFICATION_SEND_VIEW
    UNION ALL
    SELECT 
        "USER_ID",
        "PLATFORM",
        "APP_GROUP_ID",
        "CAMPAIGN_ID",
        "MESSAGE_VARIATION_ID",
        "TIME"
    FROM BRAZE_USER_EVENT_DEMO_DATASET.PUBLIC.USERS_MESSAGES_PUSHNOTIFICATION_BOUNCE_VIEW
    UNION ALL
    SELECT 
        "USER_ID",
        "PLATFORM",
        "APP_GROUP_ID",
        "CAMPAIGN_ID",
        "MESSAGE_VARIATION_ID",
        "TIME"
    FROM BRAZE_USER_EVENT_DEMO_DATASET.PUBLIC.USERS_MESSAGES_PUSHNOTIFICATION_OPEN_VIEW
    UNION ALL
    SELECT 
        "USER_ID",
        "PLATFORM",
        "APP_GROUP_ID",
        "CAMPAIGN_ID",
        "MESSAGE_VARIATION_ID",
        "TIME"
    FROM BRAZE_USER_EVENT_DEMO_DATASET.PUBLIC.USERS_MESSAGES_PUSHNOTIFICATION_INFLUENCEDOPEN_VIEW
) AS ALL_EVENTS
WHERE "TIME" >= 1685616000 AND "TIME" <= 1685619600 -- Specifies June 1, 2023, 8:00 AM to 9:00 AM
GROUP BY 
    "USER_ID",
    "PLATFORM",
    "APP_GROUP_ID",
    "CAMPAIGN_ID",
    "MESSAGE_VARIATION_ID"
LIMIT 100;