SELECT 
    "USER_ID", 
    "PLATFORM", 
    "CAMPAIGN_ID", 
    "MESSAGE_VARIATION_API_ID", 
    "EVENT_TYPE", 
    "TIME"
FROM (
    SELECT 
        "USER_ID", 
        "PLATFORM", 
        "CAMPAIGN_ID", 
        "MESSAGE_VARIATION_API_ID", 
        'OPEN' AS "EVENT_TYPE", 
        "TIME"
    FROM "BRAZE_USER_EVENT_DEMO_DATASET"."PUBLIC"."USERS_MESSAGES_PUSHNOTIFICATION_OPEN_VIEW"
    UNION ALL
    SELECT 
        "USER_ID", 
        "PLATFORM", 
        "CAMPAIGN_ID", 
        "MESSAGE_VARIATION_API_ID", 
        'INFLUENCED_OPEN' AS "EVENT_TYPE", 
        "TIME"
    FROM "BRAZE_USER_EVENT_DEMO_DATASET"."PUBLIC"."USERS_MESSAGES_PUSHNOTIFICATION_INFLUENCEDOPEN_VIEW"
    UNION ALL
    SELECT 
        "USER_ID", 
        "PLATFORM", 
        "CAMPAIGN_ID", 
        "MESSAGE_VARIATION_API_ID", 
        'SEND' AS "EVENT_TYPE", 
        "TIME"
    FROM "BRAZE_USER_EVENT_DEMO_DATASET"."PUBLIC"."USERS_MESSAGES_PUSHNOTIFICATION_SEND_VIEW"
    UNION ALL
    SELECT 
        "USER_ID", 
        "PLATFORM", 
        "CAMPAIGN_ID", 
        "MESSAGE_VARIATION_API_ID", 
        'BOUNCE' AS "EVENT_TYPE", 
        "TIME"
    FROM "BRAZE_USER_EVENT_DEMO_DATASET"."PUBLIC"."USERS_MESSAGES_PUSHNOTIFICATION_BOUNCE_VIEW"
) AS COMBINED_EVENTS
WHERE 
    "TIME" >= 1685616000 AND "TIME" <= 1685619600
LIMIT 20;