SELECT 
    "USER_ID",
    COUNT(*) AS "NOTIFICATION_COUNT",
    "PLATFORM",
    "CAMPAIGN_ID",
    "APP_GROUP_ID"
FROM (
    SELECT "USER_ID", "PLATFORM", "CAMPAIGN_ID", "APP_GROUP_ID", "TIME"
    FROM "BRAZE_USER_EVENT_DEMO_DATASET"."PUBLIC"."USERS_MESSAGES_PUSHNOTIFICATION_SEND_VIEW"
    UNION ALL
    SELECT "USER_ID", "PLATFORM", "CAMPAIGN_ID", "APP_GROUP_ID", "TIME"
    FROM "BRAZE_USER_EVENT_DEMO_DATASET"."PUBLIC"."USERS_MESSAGES_PUSHNOTIFICATION_BOUNCE_VIEW"
    UNION ALL
    SELECT "USER_ID", "PLATFORM", "CAMPAIGN_ID", "APP_GROUP_ID", "TIME"
    FROM "BRAZE_USER_EVENT_DEMO_DATASET"."PUBLIC"."USERS_MESSAGES_PUSHNOTIFICATION_OPEN_VIEW"
    UNION ALL
    SELECT "USER_ID", "PLATFORM", "CAMPAIGN_ID", "APP_GROUP_ID", "TIME"
    FROM "BRAZE_USER_EVENT_DEMO_DATASET"."PUBLIC"."USERS_MESSAGES_PUSHNOTIFICATION_INFLUENCEDOPEN_VIEW"
) AS ALL_EVENTS
WHERE "TIME" BETWEEN 1685606400 AND 1685610000
GROUP BY "USER_ID", "PLATFORM", "CAMPAIGN_ID", "APP_GROUP_ID"
ORDER BY "NOTIFICATION_COUNT" DESC
LIMIT 100;