SELECT t1."ID_RSSD", 
       t2."NAME", 
       t3."VALUE" AS "TOTAL_ASSETS", 
       ROUND((1 - t1."VALUE"), 4) AS "PERCENT_UNINSURED_ASSETS"
FROM "FINANCE__ECONOMICS"."CYBERSYN"."FINANCIAL_INSTITUTION_TIMESERIES" t1
JOIN "FINANCE__ECONOMICS"."CYBERSYN"."FINANCIAL_INSTITUTION_ENTITIES" t2
  ON t1."ID_RSSD" = t2."ID_RSSD"
JOIN "FINANCE__ECONOMICS"."CYBERSYN"."FINANCIAL_INSTITUTION_TIMESERIES" t3
  ON t1."ID_RSSD" = t3."ID_RSSD"
WHERE t1."VARIABLE_NAME" = '% Insured (Estimated)'
  AND t1."DATE" = '2022-12-31'
  AND t2."IS_ACTIVE" = TRUE
  AND t3."VARIABLE" = 'ASSET'
  AND t3."DATE" = '2022-12-31'
  AND t3."VALUE" > 10000000000
ORDER BY "PERCENT_UNINSURED_ASSETS" DESC NULLS LAST
LIMIT 10;