SELECT e."NAME", 
       e."FDIC_CERT", 
       e."ID_RSSD", 
       1 - t."VALUE" AS "UNINSURED_PERCENTAGE", 
       t."DATE" 
FROM "FINANCE__ECONOMICS"."CYBERSYN"."FINANCIAL_INSTITUTION_ENTITIES" e 
JOIN "FINANCE__ECONOMICS"."CYBERSYN"."FINANCIAL_INSTITUTION_TIMESERIES" t 
ON e."ID_RSSD" = t."ID_RSSD" 
WHERE e."IS_ACTIVE" = TRUE 
  AND t."VARIABLE_NAME" = '% Insured (Estimated)' 
  AND t."DATE" = '2022-12-31' 
  AND e."ID_RSSD" IN (
      SELECT DISTINCT "ID_RSSD" 
      FROM "FINANCE__ECONOMICS"."CYBERSYN"."FINANCIAL_INSTITUTION_TIMESERIES" 
      WHERE "VARIABLE_NAME" LIKE '%Assets%' 
        AND "DATE" = '2022-12-31' 
        AND "VALUE" > 10000000000
  )
ORDER BY "UNINSURED_PERCENTAGE" DESC NULLS LAST 
LIMIT 10;