SELECT 
    e."NAME" AS "BANK_NAME",
    ROUND((1 - CAST(insured."VALUE" AS FLOAT)) * 100, 2) AS "PERCENT_UNINSURED"
FROM "FINANCE__ECONOMICS"."CYBERSYN"."FINANCIAL_INSTITUTION_TIMESERIES" t
JOIN "FINANCE__ECONOMICS"."CYBERSYN"."FINANCIAL_INSTITUTION_TIMESERIES" insured
    ON t."ID_RSSD" = insured."ID_RSSD"
JOIN "FINANCE__ECONOMICS"."CYBERSYN"."FINANCIAL_INSTITUTION_ENTITIES" e
    ON t."ID_RSSD" = CAST(e."ID_RSSD" AS TEXT)
WHERE t."VARIABLE_NAME" ILIKE '%Asset%' -- Broaden "VARIABLE_NAME" filter
  AND t."DATE" = '2022-12-31'
  AND CAST(t."VALUE" AS FLOAT) > 10000000000 -- Filter for assets > $10 billion
  AND insured."VARIABLE_NAME" ILIKE '%Insured%' -- Broaden "VARIABLE_NAME" filter for insured
  AND insured."DATE" = '2022-12-31'
  AND e."IS_ACTIVE" = TRUE -- Only active banks
ORDER BY "PERCENT_UNINSURED" DESC NULLS LAST
LIMIT 10;