SELECT 
    A."NAME" AS "BANK_NAME", 
    ROUND((1 - B."VALUE") * 100, 4) AS "PERCENT_UNINSURED" 
FROM "FINANCE__ECONOMICS"."CYBERSYN"."FINANCIAL_INSTITUTION_ENTITIES" A 
JOIN "FINANCE__ECONOMICS"."CYBERSYN"."FINANCIAL_INSTITUTION_TIMESERIES" B 
    ON A."ID_RSSD" = B."ID_RSSD" 
JOIN "FINANCE__ECONOMICS"."CYBERSYN"."FINANCIAL_INSTITUTION_TIMESERIES" D 
    ON A."ID_RSSD" = D."ID_RSSD" 
WHERE A."IS_ACTIVE" = TRUE 
  AND B."VARIABLE_NAME" = '% Insured (Estimated)' 
  AND D."VARIABLE_NAME" ILIKE '%asset%' 
  AND D."VALUE" > 10000000000 
  AND B."DATE" = '2022-12-31' 
  AND D."DATE" = '2022-12-31' 
ORDER BY "PERCENT_UNINSURED" DESC NULLS LAST 
LIMIT 10;