SELECT t1."NAME" AS "BANK_NAME",
       (1 - t3."VALUE") * 100 AS "PERCENT_UNINSURED"
FROM "FINANCE__ECONOMICS"."CYBERSYN"."FINANCIAL_INSTITUTION_ENTITIES" t1
JOIN "FINANCE__ECONOMICS"."CYBERSYN"."FINANCIAL_INSTITUTION_TIMESERIES" t2
ON CAST(t1."ID_RSSD" AS TEXT) = t2."ID_RSSD"
JOIN "FINANCE__ECONOMICS"."CYBERSYN"."FINANCIAL_INSTITUTION_TIMESERIES" t3
ON CAST(t1."ID_RSSD" AS TEXT) = t3."ID_RSSD"
WHERE t1."IS_ACTIVE" = TRUE
  AND t2."VARIABLE_NAME" ILIKE '%asset%'
  AND t2."VALUE" > 10000000000 -- Assets exceeding $10 billion
  AND t3."VARIABLE_NAME" ILIKE '%insured (estimated)%'
  AND t3."DATE" = '2022-12-31'
ORDER BY (1 - t3."VALUE") DESC NULLS LAST
LIMIT 10;