WITH LARGEST_ZIP AS (
    SELECT "ZIP", COUNT("ADDRESS_ID") AS "ADDRESS_COUNT"
    FROM "US_ADDRESSES__POI"."CYBERSYN"."US_ADDRESSES"
    WHERE "STATE" = 'FL'
    GROUP BY "ZIP"
    ORDER BY "ADDRESS_COUNT" DESC NULLS LAST
    LIMIT 1
),
TOP_ADDRESSES AS (
    SELECT "NUMBER", "STREET", "STREET_TYPE", "LATITUDE"
    FROM "US_ADDRESSES__POI"."CYBERSYN"."US_ADDRESSES"
    WHERE "STATE" = 'FL'
      AND "ZIP" IN (SELECT "ZIP" FROM LARGEST_ZIP)
    ORDER BY "LATITUDE" DESC NULLS LAST
    LIMIT 10
)
SELECT "NUMBER", "STREET", "STREET_TYPE"
FROM TOP_ADDRESSES;