SELECT "NUMBER", "STREET", "STREET_TYPE" 
FROM "US_ADDRESSES__POI"."CYBERSYN"."US_ADDRESSES"
WHERE "ZIP" = (
    SELECT "ZIP"
    FROM (
        SELECT "ZIP", COUNT("ADDRESS_ID") AS "ADDRESS_COUNT"
        FROM "US_ADDRESSES__POI"."CYBERSYN"."US_ADDRESSES"
        WHERE "STATE" = 'FL'
        GROUP BY "ZIP"
        ORDER BY "ADDRESS_COUNT" DESC
        LIMIT 1
    )
)
ORDER BY "LATITUDE" DESC
LIMIT 10;