SELECT 
    "NUMBER", 
    "STREET", 
    "STREET_TYPE", 
    "LATITUDE", 
    "LONGITUDE", 
    "CITY", 
    "STATE", 
    "ZIP"
FROM "US_ADDRESSES__POI"."CYBERSYN"."US_ADDRESSES" 
WHERE "ZIP" = '33033'
ORDER BY "LATITUDE" DESC NULLS LAST 
LIMIT 10;