SELECT "NUMBER", "STREET", "STREET_TYPE", "LATITUDE"
FROM "US_ADDRESSES__POI"."CYBERSYN"."US_ADDRESSES"
WHERE "ZIP" = (
    -- Subquery to identify the largest ZIP code in Florida
    SELECT "ZIP"
    FROM "US_ADDRESSES__POI"."CYBERSYN"."US_ADDRESSES"
    WHERE "STATE" = 'FL'
    GROUP BY "ZIP"
    ORDER BY COUNT(*) DESC NULLS LAST
    LIMIT 1
)
AND "STATE" = 'FL'
ORDER BY "LATITUDE" DESC NULLS LAST
LIMIT 10;