WITH Filtered_Items AS (
    SELECT "ITEMS"
    FROM (
        SELECT "ITEMS" 
        FROM "GA4"."GA4_OBFUSCATED_SAMPLE_ECOMMERCE"."EVENTS_20201204"
        UNION
        SELECT "ITEMS" 
        FROM "GA4"."GA4_OBFUSCATED_SAMPLE_ECOMMERCE"."EVENTS_20201207"
        UNION
        SELECT "ITEMS" 
        FROM "GA4"."GA4_OBFUSCATED_SAMPLE_ECOMMERCE"."EVENTS_20201211"
        UNION
        SELECT "ITEMS" 
        FROM "GA4"."GA4_OBFUSCATED_SAMPLE_ECOMMERCE"."EVENTS_20201212"
        UNION
        SELECT "ITEMS" 
        FROM "GA4"."GA4_OBFUSCATED_SAMPLE_ECOMMERCE"."EVENTS_20201213"
        UNION
        SELECT "ITEMS" 
        FROM "GA4"."GA4_OBFUSCATED_SAMPLE_ECOMMERCE"."EVENTS_20201215"
        UNION
        SELECT "ITEMS" 
        FROM "GA4"."GA4_OBFUSCATED_SAMPLE_ECOMMERCE"."EVENTS_20201222"
        UNION
        SELECT "ITEMS" 
        FROM "GA4"."GA4_OBFUSCATED_SAMPLE_ECOMMERCE"."EVENTS_20201223"
        UNION
        SELECT "ITEMS" 
        FROM "GA4"."GA4_OBFUSCATED_SAMPLE_ECOMMERCE"."EVENTS_20201224"
        UNION
        SELECT "ITEMS" 
        FROM "GA4"."GA4_OBFUSCATED_SAMPLE_ECOMMERCE"."EVENTS_20201228"
    ) t, LATERAL FLATTEN(input => t."ITEMS") f
    WHERE f.value::VARIANT:"item_name"::STRING = 'Google Navy Speckled Tee'
)
SELECT f1.value::VARIANT:"item_name"::STRING AS "Product_Name", 
       f1.value::VARIANT:"item_id"::STRING AS "Product_ID", 
       SUM(f1.value::VARIANT:"quantity"::NUMBER) AS "Total_Quantity"
FROM (
    SELECT "ITEMS" 
    FROM "GA4"."GA4_OBFUSCATED_SAMPLE_ECOMMERCE"."EVENTS_20201204"
    UNION
    SELECT "ITEMS" 
    FROM "GA4"."GA4_OBFUSCATED_SAMPLE_ECOMMERCE"."EVENTS_20201207"
    UNION
    SELECT "ITEMS" 
    FROM "GA4"."GA4_OBFUSCATED_SAMPLE_ECOMMERCE"."EVENTS_20201211"
    UNION
    SELECT "ITEMS" 
    FROM "GA4"."GA4_OBFUSCATED_SAMPLE_ECOMMERCE"."EVENTS_20201212"
    UNION
    SELECT "ITEMS" 
    FROM "GA4"."GA4_OBFUSCATED_SAMPLE_ECOMMERCE"."EVENTS_20201213"
    UNION
    SELECT "ITEMS" 
    FROM "GA4"."GA4_OBFUSCATED_SAMPLE_ECOMMERCE"."EVENTS_20201215"
    UNION
    SELECT "ITEMS" 
    FROM "GA4"."GA4_OBFUSCATED_SAMPLE_ECOMMERCE"."EVENTS_20201222"
    UNION
    SELECT "ITEMS" 
    FROM "GA4"."GA4_OBFUSCATED_SAMPLE_ECOMMERCE"."EVENTS_20201223"
    UNION
    SELECT "ITEMS" 
    FROM "GA4"."GA4_OBFUSCATED_SAMPLE_ECOMMERCE"."EVENTS_20201224"
    UNION
    SELECT "ITEMS" 
    FROM "GA4"."GA4_OBFUSCATED_SAMPLE_ECOMMERCE"."EVENTS_20201228"
) t, LATERAL FLATTEN(input => t."ITEMS") f1
WHERE f1.value::VARIANT:"item_name"::STRING != 'Google Navy Speckled Tee'
  AND EXISTS (
      SELECT 1
      FROM Filtered_Items fi, LATERAL FLATTEN(input => fi."ITEMS") f2
      WHERE f2.value::VARIANT:"item_name"::STRING = f1.value::VARIANT:"item_name"::STRING
  )
GROUP BY "Product_Name", "Product_ID"
ORDER BY "Total_Quantity" DESC NULLS LAST
LIMIT 1;