WITH all_events AS (
    -- Union all events data for December 2020
    SELECT *
    FROM "GA4"."GA4_OBFUSCATED_SAMPLE_ECOMMERCE"."EVENTS_20201201" 
    UNION ALL 
    SELECT * 
    FROM "GA4"."GA4_OBFUSCATED_SAMPLE_ECOMMERCE"."EVENTS_20201202" 
    UNION ALL 
    SELECT * 
    FROM "GA4"."GA4_OBFUSCATED_SAMPLE_ECOMMERCE"."EVENTS_20201203" 
    UNION ALL 
    SELECT * 
    FROM "GA4"."GA4_OBFUSCATED_SAMPLE_ECOMMERCE"."EVENTS_20201204" 
    UNION ALL 
    SELECT * 
    FROM "GA4"."GA4_OBFUSCATED_SAMPLE_ECOMMERCE"."EVENTS_20201205" 
    UNION ALL 
    SELECT * 
    FROM "GA4"."GA4_OBFUSCATED_SAMPLE_ECOMMERCE"."EVENTS_20201206" 
    UNION ALL 
    SELECT * 
    FROM "GA4"."GA4_OBFUSCATED_SAMPLE_ECOMMERCE"."EVENTS_20201207" 
    UNION ALL 
    SELECT * 
    FROM "GA4"."GA4_OBFUSCATED_SAMPLE_ECOMMERCE"."EVENTS_20201208" 
    UNION ALL 
    SELECT * 
    FROM "GA4"."GA4_OBFUSCATED_SAMPLE_ECOMMERCE"."EVENTS_20201209" 
    UNION ALL 
    SELECT * 
    FROM "GA4"."GA4_OBFUSCATED_SAMPLE_ECOMMERCE"."EVENTS_20201210" 
    UNION ALL 
    SELECT * 
    FROM "GA4"."GA4_OBFUSCATED_SAMPLE_ECOMMERCE"."EVENTS_20201211" 
    UNION ALL 
    SELECT * 
    FROM "GA4"."GA4_OBFUSCATED_SAMPLE_ECOMMERCE"."EVENTS_20201212" 
    UNION ALL 
    SELECT * 
    FROM "GA4"."GA4_OBFUSCATED_SAMPLE_ECOMMERCE"."EVENTS_20201213" 
    UNION ALL 
    SELECT * 
    FROM "GA4"."GA4_OBFUSCATED_SAMPLE_ECOMMERCE"."EVENTS_20201214" 
    UNION ALL 
    SELECT * 
    FROM "GA4"."GA4_OBFUSCATED_SAMPLE_ECOMMERCE"."EVENTS_20201215" 
    UNION ALL 
    SELECT * 
    FROM "GA4"."GA4_OBFUSCATED_SAMPLE_ECOMMERCE"."EVENTS_20201216" 
    UNION ALL 
    SELECT * 
    FROM "GA4"."GA4_OBFUSCATED_SAMPLE_ECOMMERCE"."EVENTS_20201217" 
    UNION ALL 
    SELECT * 
    FROM "GA4"."GA4_OBFUSCATED_SAMPLE_ECOMMERCE"."EVENTS_20201218" 
    UNION ALL 
    SELECT * 
    FROM "GA4"."GA4_OBFUSCATED_SAMPLE_ECOMMERCE"."EVENTS_20201219" 
    UNION ALL 
    SELECT * 
    FROM "GA4"."GA4_OBFUSCATED_SAMPLE_ECOMMERCE"."EVENTS_20201220" 
    UNION ALL 
    SELECT * 
    FROM "GA4"."GA4_OBFUSCATED_SAMPLE_ECOMMERCE"."EVENTS_20201221" 
    UNION ALL 
    SELECT * 
    FROM "GA4"."GA4_OBFUSCATED_SAMPLE_ECOMMERCE"."EVENTS_20201222" 
    UNION ALL 
    SELECT * 
    FROM "GA4"."GA4_OBFUSCATED_SAMPLE_ECOMMERCE"."EVENTS_20201223" 
    UNION ALL 
    SELECT * 
    FROM "GA4"."GA4_OBFUSCATED_SAMPLE_ECOMMERCE"."EVENTS_20201224" 
    UNION ALL 
    SELECT * 
    FROM "GA4"."GA4_OBFUSCATED_SAMPLE_ECOMMERCE"."EVENTS_20201225" 
    UNION ALL 
    SELECT * 
    FROM "GA4"."GA4_OBFUSCATED_SAMPLE_ECOMMERCE"."EVENTS_20201226" 
    UNION ALL 
    SELECT * 
    FROM "GA4"."GA4_OBFUSCATED_SAMPLE_ECOMMERCE"."EVENTS_20201227" 
    UNION ALL 
    SELECT * 
    FROM "GA4"."GA4_OBFUSCATED_SAMPLE_ECOMMERCE"."EVENTS_20201228" 
    UNION ALL 
    SELECT * 
    FROM "GA4"."GA4_OBFUSCATED_SAMPLE_ECOMMERCE"."EVENTS_20201229" 
    UNION ALL 
    SELECT * 
    FROM "GA4"."GA4_OBFUSCATED_SAMPLE_ECOMMERCE"."EVENTS_20201230" 
    UNION ALL 
    SELECT * 
    FROM "GA4"."GA4_OBFUSCATED_SAMPLE_ECOMMERCE"."EVENTS_20201231"
),
events_with_target AS (
    -- Filter events containing the 'Google Navy Speckled Tee'
    SELECT DISTINCT t."EVENT_BUNDLE_SEQUENCE_ID"
    FROM all_events t, 
    LATERAL FLATTEN(input => t."ITEMS") f
    WHERE f.value::VARIANT:"item_name"::STRING ILIKE '%Google%Navy%Speckled%Tee%'
),
related_items AS (
    -- Extract other products purchased alongside the target item
    SELECT f.value::VARIANT:"item_name"::STRING AS "ITEM_NAME", 
           SUM(f.value::VARIANT:"quantity"::NUMBER) AS "TOTAL_QUANTITY"
    FROM all_events t, 
    LATERAL FLATTEN(input => t."ITEMS") f
    WHERE t."EVENT_BUNDLE_SEQUENCE_ID" IN (SELECT "EVENT_BUNDLE_SEQUENCE_ID" FROM events_with_target)
      AND f.value::VARIANT:"item_name"::STRING NOT ILIKE '%Google%Navy%Speckled%Tee%'
    GROUP BY f.value::VARIANT:"item_name"::STRING
)
SELECT "ITEM_NAME", "TOTAL_QUANTITY"
FROM related_items
ORDER BY "TOTAL_QUANTITY" DESC NULLS LAST
LIMIT 1;