SELECT
    YEAR("DATE_OF_LOSS") AS "YEAR_OF_LOSS",
    SUM("BUILDING_DAMAGE_AMOUNT")  AS "TOTAL_BUILDING_DAMAGE_AMOUNT",
    SUM("CONTENTS_DAMAGE_AMOUNT")  AS "TOTAL_CONTENTS_DAMAGE_AMOUNT"
FROM WEATHER__ENVIRONMENT.CYBERSYN.FEMA_NATIONAL_FLOOD_INSURANCE_PROGRAM_CLAIM_INDEX
WHERE "NFIP_COMMUNITY_NAME" ILIKE 'City Of New York'
  AND YEAR("DATE_OF_LOSS") BETWEEN 2010 AND 2019
GROUP BY "YEAR_OF_LOSS"
ORDER BY "YEAR_OF_LOSS";