SELECT
    EXTRACT(year FROM "DATE_OF_LOSS")                         AS "YEAR_OF_LOSS",
    SUM("BUILDING_DAMAGE_AMOUNT")                             AS "TOTAL_BUILDING_DAMAGE_AMOUNT",
    SUM("CONTENTS_DAMAGE_AMOUNT")                             AS "TOTAL_CONTENTS_DAMAGE_AMOUNT"
FROM WEATHER__ENVIRONMENT.CYBERSYN.FEMA_NATIONAL_FLOOD_INSURANCE_PROGRAM_CLAIM_INDEX
WHERE UPPER("NFIP_COMMUNITY_NAME") = 'CITY OF NEW YORK'
  AND "DATE_OF_LOSS" >= '2010-01-01'
  AND "DATE_OF_LOSS" <  '2020-01-01'
GROUP BY EXTRACT(year FROM "DATE_OF_LOSS")
ORDER BY "YEAR_OF_LOSS" ASC;