SELECT
    EXTRACT(year FROM "DATE_OF_LOSS") AS "LOSS_YEAR",
    SUM("BUILDING_DAMAGE_AMOUNT")  AS "TOTAL_BUILDING_DAMAGE_AMOUNT",
    SUM("CONTENTS_DAMAGE_AMOUNT") AS "TOTAL_CONTENTS_DAMAGE_AMOUNT"
FROM WEATHER__ENVIRONMENT.CYBERSYN.FEMA_NATIONAL_FLOOD_INSURANCE_PROGRAM_CLAIM_INDEX
WHERE "NFIP_COMMUNITY_NAME" = 'City Of New York'
  AND "DATE_OF_LOSS" >= '2010-01-01'
  AND "DATE_OF_LOSS" <  '2020-01-01'
GROUP BY EXTRACT(year FROM "DATE_OF_LOSS")
ORDER BY "LOSS_YEAR";