SELECT 
    EXTRACT(MONTH FROM TO_TIMESTAMP("order_purchase_timestamp", 'YYYY-MM-DD HH24:MI:SS')) AS "month",
    SUM(CASE WHEN EXTRACT(YEAR FROM TO_TIMESTAMP("order_purchase_timestamp", 'YYYY-MM-DD HH24:MI:SS')) = 2016 THEN 1 ELSE 0 END) AS "2016",
    SUM(CASE WHEN EXTRACT(YEAR FROM TO_TIMESTAMP("order_purchase_timestamp", 'YYYY-MM-DD HH24:MI:SS')) = 2017 THEN 1 ELSE 0 END) AS "2017",
    SUM(CASE WHEN EXTRACT(YEAR FROM TO_TIMESTAMP("order_purchase_timestamp", 'YYYY-MM-DD HH24:MI:SS')) = 2018 THEN 1 ELSE 0 END) AS "2018"
FROM 
    "BRAZILIAN_E_COMMERCE"."BRAZILIAN_E_COMMERCE"."OLIST_ORDERS"
WHERE 
    "order_status" = 'delivered'
    AND EXTRACT(YEAR FROM TO_TIMESTAMP("order_purchase_timestamp", 'YYYY-MM-DD HH24:MI:SS')) IN (2016, 2017, 2018)
GROUP BY 
    1
ORDER BY 
    1;