SELECT YEAR("DATE_OF_LOSS") AS "YEAR_OF_LOSS", 
       SUM("BUILDING_DAMAGE_AMOUNT") AS "TOTAL_BUILDING_DAMAGE", 
       SUM("CONTENTS_DAMAGE_AMOUNT") AS "TOTAL_CONTENTS_DAMAGE" 
FROM WEATHER__ENVIRONMENT.CYBERSYN.FEMA_NATIONAL_FLOOD_INSURANCE_PROGRAM_CLAIM_INDEX 
WHERE "NFIP_COMMUNITY_NAME" = 'City Of New York' 
  AND "DATE_OF_LOSS" BETWEEN '2010-01-01' AND '2019-12-31' 
GROUP BY YEAR("DATE_OF_LOSS") 
ORDER BY "YEAR_OF_LOSS";