SELECT 
    EXTRACT(YEAR FROM "DATE_OF_LOSS") AS "YEAR", 
    SUM("BUILDING_DAMAGE_AMOUNT") AS "TOTAL_BUILDING_DAMAGE",
    SUM("CONTENTS_DAMAGE_AMOUNT") AS "TOTAL_CONTENTS_DAMAGE"
FROM WEATHER__ENVIRONMENT.CYBERSYN.FEMA_NATIONAL_FLOOD_INSURANCE_PROGRAM_CLAIM_INDEX
WHERE "DATE_OF_LOSS" BETWEEN '2010-01-01' AND '2019-12-31'
  AND "NFIP_COMMUNITY_NAME" = 'City Of New York'
GROUP BY EXTRACT(YEAR FROM "DATE_OF_LOSS")
ORDER BY "YEAR";