SELECT DATE_PART('YEAR', "DATE_OF_LOSS") AS "YEAR", 
       SUM("BUILDING_DAMAGE_AMOUNT") AS "TOTAL_BUILDING_DAMAGE_AMOUNT", 
       SUM("CONTENTS_DAMAGE_AMOUNT") AS "TOTAL_CONTENTS_DAMAGE_AMOUNT"
FROM WEATHER__ENVIRONMENT.CYBERSYN.FEMA_NATIONAL_FLOOD_INSURANCE_PROGRAM_CLAIM_INDEX 
WHERE "NFIP_COMMUNITY_NAME" = 'City Of New York' 
  AND "DATE_OF_LOSS" BETWEEN '2010-01-01' AND '2019-12-31' 
GROUP BY DATE_PART('YEAR', "DATE_OF_LOSS") 
ORDER BY "YEAR";