SELECT 
    "POSTAL_CODE", 
    "DATE_VALID_STD", 
    "TOT_SNOWFALL_IN" 
FROM 
    "GLOBAL_WEATHER__CLIMATE_DATA_FOR_BI"."STANDARD_TILE"."HISTORY_DAY" 
WHERE 
    "COUNTRY" = 'US' 
    AND "TOT_SNOWFALL_IN" > 6 
    AND "DATE_VALID_STD" BETWEEN DATEADD(DAY, 14, DATEADD(YEAR, -1, DATE_TRUNC(YEAR, CURRENT_DATE))) 
                            AND DATEADD(DAY, 20, DATEADD(YEAR, -1, DATE_TRUNC(YEAR, CURRENT_DATE)))
ORDER BY 
    "POSTAL_CODE", 
    "DATE_VALID_STD";