WITH FL_ZIP_COUNTS AS (
    SELECT 
        "ZIP",
        COUNT(*) AS "ADDRESS_COUNT"
    FROM "US_ADDRESSES__POI"."CYBERSYN"."US_ADDRESSES"
    WHERE "STATE" = 'FL'
    GROUP BY "ZIP"
),
LARGEST_FL_ZIP AS (
    SELECT "ZIP"
    FROM FL_ZIP_COUNTS
    ORDER BY "ADDRESS_COUNT" DESC NULLS LAST
    LIMIT 1
)

SELECT
    "NUMBER"        AS "ADDRESS_NUMBER",
    "STREET"        AS "STREET_NAME",
    "STREET_TYPE"
FROM "US_ADDRESSES__POI"."CYBERSYN"."US_ADDRESSES"
WHERE "STATE" = 'FL'
  AND "ZIP" = (SELECT "ZIP" FROM LARGEST_FL_ZIP)
ORDER BY "LATITUDE" DESC NULLS LAST
LIMIT 10;