WITH "FILTERED_USERS" AS (
    SELECT 
        "id",
        "age"
    FROM THELOOK_ECOMMERCE.THELOOK_ECOMMERCE."USERS"
    WHERE "age" IS NOT NULL
      AND TO_DATE(TO_TIMESTAMP("created_at" / 1000000)) BETWEEN '2019-01-01' AND '2022-04-30'
), 
"AGE_EXTREMES" AS (
    SELECT 
        MAX("age") AS "MAX_AGE",
        MIN("age") AS "MIN_AGE"
    FROM "FILTERED_USERS"
), 
"COUNTS" AS (
    SELECT 
        SUM(CASE WHEN fu."age" = ae."MAX_AGE" THEN 1 ELSE 0 END) AS "CNT_OLDEST",
        SUM(CASE WHEN fu."age" = ae."MIN_AGE" THEN 1 ELSE 0 END) AS "CNT_YOUNGEST"
    FROM "FILTERED_USERS" fu
    CROSS JOIN "AGE_EXTREMES" ae
)
SELECT
    "CNT_OLDEST",
    "CNT_YOUNGEST",
    "CNT_OLDEST" - "CNT_YOUNGEST" AS "DIFFERENCE_IN_COUNT"
FROM "COUNTS";